trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: NeuVectorScan@1
  inputs:
    controllerType: 'external'
    neuvectorController: 'neuvector_controller'
    containerRegistry: 'registry_to_scan'
    repository: 'library/alpine'
    tag: '3.12'
    failOnHighSeverityThreshold: true
    highSeverityThreshold: '100'
    failOnMediumSeverityThreshold: true
    mediumSeverityThreshold: '200'
